version: 2.0
jobs:
  build:
    docker:
      - image: outpostuniverse/nas2d-circleci:1.1
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update
      - run:
          name: "Build"
          command: make --keep-going
