version: 2.1

commands:
  build:
    steps:
      - checkout
      - run: git submodule update --init nas2d-core/
      - run: make --keep-going --jobs 2 CXXFLAGS_EXTRA="-Werror" nas2d
      - run: make --keep-going --jobs 2 CXXFLAGS_EXTRA="-Werror"
      - run: make package
      - store_artifacts:
          path: .build/package/

jobs:
  build-linux:
    docker:
      - image: outpostuniverse/nas2d:1.4
    steps:
      - build
  build-linux-gcc:
    docker:
      - image: outpostuniverse/nas2d-gcc:1.2
    environment:
      WARN_EXTRA: -Wsuggest-override
    steps:
      - build
  build-linux-clang:
    docker:
      - image: outpostuniverse/nas2d-clang:1.1
    environment:
      WARN_EXTRA: -Wimplicit-int-conversion -Wunreachable-code -Wunreachable-code-return -Wunreachable-code-break -Wextra-semi-stmt -Wnewline-eof -Wdocumentation -Wheader-hygiene -Winconsistent-missing-destructor-override -Wdeprecated-copy-dtor -Wformat-nonliteral
    steps:
      - build
  build-linux-mingw:
    docker:
      - image: outpostuniverse/nas2d-mingw:1.5
    steps:
      - checkout
      - run: git submodule update --init nas2d-core/
      - run: make --keep-going --jobs 2 CXXFLAGS_EXTRA="-Werror" intermediate

workflows:
  build:
    jobs:
      - build-linux
      - build-linux-gcc
      - build-linux-clang
      - build-linux-mingw
