version: 2.0
jobs:
  build:
    docker:
      - image: outpostuniverse/nas2d-circleci:1.1
    steps:
      - checkout
      - run: git submodule update --init
      - run:
          name: "Build"
          command: make --keep-going
